### ISSUE TITLE
The package cannot be installed

### ISSUE THREAD

**Issue by ChongWu-Biostat** [lingxuez/sLED#1]
Dear author,
The package cannot be installed. It seems you need change the documents accordingly.
Thanks,
Chong

**Comment by lingxuez** [comment]
Hi Chong,

Can you provide more information on how the installation failed? Are you using a Mac OS?
I've added an alternative option to install through terminal in README, can you try to see whether it works for you? I've tested on my PC and it went through as well.

Thanks,
Lingxue

**Comment by ChongWu-Biostat** [comment]
Here is the error message:

> library("devtools")
> devtools::install("/path/to/sLEDpackage")
> Error: Can't find '/path/to/sLEDpackage'.

I think the document should be changed somehow.

Thanks,
Chong

**Comment by lingxuez** [comment]
Hi Chong,

Thanks for the feedback. The "path/to/sLEDpackage" should be changed to the path where you put the downloaded file in your computer. This should fix the error. Please let me know if you encounter other problems.

Thanks,
Lingxue

**Comment by ChongWu-Biostat** [comment]
Thanks for your prompt and warm reply. It works now.
Thanks,
Chong

**Comment by ChongWu-Biostat** [comment]
Hi Lingxue,
The package can be installed in unix or Linux system. Hope this information is helpful.
Thanks,
Chong

**Comment by lingxuez** [comment]
Thank you, it's good to know.

Best,
Lingxue
